### ISSUE TITLE
Server Specs

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#10]
Hi @hapiben, 

We're looking to move some of our SuppleJack exploration to the cloud soon. We're considering two different approaches to this.

Were we to follow the production docs at http://digitalnz.github.io/supplejack/start/production-install.html  can you recommend minimum server specs for us, or other items of interest?

Our other approach (which seems more likely at this time) is replicating the docker repo and adding a front end to display content. @revanar has made some progress with this. 

Thanks, 

D

**Comment by hapiben** [comment]
Hi @telezoic,

With regards to server specs, it depends on many factors such as traffic, the number of records to store and number of apps that will run on a single server.

Using DigitalOcean's [pricing](https://www.digitalocean.com/pricing/) as a reference, you're good with $20/mo. Make sure to have swap space for memory as well. If you can get 8GB of RAM and 4 CPU that would be great (given that this is production).

The Manager/Worker can harvest from a file such as XML. If you're planning to harvest a file, you need more CPUs. Also, consider if you're harvesting thousands of records in a single parser (100k plus).

Another setup is to have two or more small to medium servers load-balanced.

In terms of deployment, you can stick with Docker if that's easier. We have done SJ Docker deployment before using Cloud66 + Azure and it works fine. Most of the instances that we have here for DigitalNZ, we deploy it using the documentation because we already have Chef to configure the servers.

Hope it answered your questions. Let me know if you have more.

Ben

**Comment by telezoic** [comment]
Thanks @hapiben! Was your SJ docker experience in Cloud66 + Azure for production or development?
D.

**Comment by hapiben** [comment]
Hi @telezoic. It was for development.

**Comment by telezoic** [comment]
Hi @hapiben, 
I'm slowly working on bringing this docker repo to the cloud with the hopes of making it accessible to other users. I'm troubleshooting timeouts that I'm seeing shortly after creating the `docker-machine`on Digitalocean. While I'm poking at this I was looking at Cloud66 that you have mentioned above.  It looks like some pieces are not included in your service.yml files (redis/resque) is this correct? 

Thanks, 

D

**Comment by hapiben** [comment]
Hi @telezoic 

Yes. We haven't updated the `service.yml` for a while. Also, it was meant to work on Azure instance and haven't tested on DigitalOcean instances. I can try firing this up a new DO instance to test the configuration.

Ben

**Comment by telezoic** [comment]
Hi @hapiben, 
We're making a some headway here. We have two DO droplets (one with the install, the other to host the containers) and can now access the manager in the cloud.


D.

**Comment by telezoic** [comment]
Hi @hapiben, 
We are working on our cloud deployment above and have run into an error that maybe you have seen before (or perhaps you could provide a pointer to a logfile, or a suggestion for us?). When we attempt to preview a harvest after building a parser we get the following error:  

`ActiveResource::UnauthorizedAccess`

`Failed. Response code = 401. Response message = Unauthorized.`

    /bundle/gems/activeresource-4.0.0/lib/active_resource/connection.rb:140:in `handle_response'
    /bundle/gems/activeresource-4.0.0/lib/active_resource/connection.rb:123:in `request'
    /bundle/gems/activeresource-4.0.0/lib/active_resource/connection.rb:82:in `block in get'
    /bundle/gems/activeresource-4.0.0/lib/active_resource/connection.rb:216:in `with_auth'
    /bundle/gems/activeresource-4.0.0/lib/active_resource/connection.rb:82:in `get'
    /bundle/gems/activeresource-4.0.0/lib/active_resource/base.rb:990:in `find_single'
    /bundle/gems/activeresource-4.0.0/lib/active_resource/base.rb:877:in `find'
    /worker/app/models/abstract_job.rb:86:in `parser'
    /worker/app/models/harvest_job.rb:54:in `records'
    /worker/app/workers/preview_worker.rb:36:in `perform'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `call'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
    /bundle/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread' `

the target of the parser makes no difference, my firewall is wide open ;-). We've never seen this in our local deployments.

Thanks, 

D.

**Comment by telezoic** [comment]
Hi @hapiben, 

I was hoping to re-confirm the server specs you mentioned (2 years ago:))

We're getting closer to a single server production build (not docker this time). With a target of ~500,000 items and over time (a few years maybe, bringing that up to a few million). 

Would you say that the 8GB RAM/4CPU stack you mention above would suffice in a scenario like this?

Thanks, 

D.
