### ISSUE TITLE
Can't perform facet searches on custom schema fields

### ISSUE THREAD

**Issue by revanar** [DigitalNZ/supplejack_docker#11]
Hi again,

I have everything running well at this point, but last night I noticed an odd bug with my API---whenever I try to do facet searches (eg `&and[language]=en`) for fields that I've added to the schema, no results are returned.

- facet searches for schema that was part of the default supplejack schema work successfully (eg `&and[category]=Image`)
- If I do a facet search for `null` on a new schema field, it returns all ingested records---even those that have a value for that field.
- Two of the new schema fields have additional odd bugs:
    - the `format` field won't display when I select it specifically as a metadata field to be returned (ie `&fields=format`), but shows up when I request a group containing it be returned (ie `&fields=all`).
    - the `publisher` field, rather than displaying no results on a facet search, instead returns the error `No field configured for SupplejackApi::Record with name &#39;publisher&#39;`.

Attached:  The schema file I'm using.
[record_schema.txt](https://github.com/DigitalNZ/supplejack_docker/files/703117/record_schema.txt)

I know this is probably a difficult issue to understand from just what I've sent, so please ask me for whatever other information will help.  

Thank you so much for all of your help with our issues!

-Matt

**Comment by hapiben** [comment]
Hi @revanar 

For the first issue, I tried using:

```
/records.json?api_key=apikey&facets=language&fields=language,title&and[language]=mi
```

And I get `mi` records. Make sure that the records get **re-indexed** after the schema change.

For `null` facets, you can use `&without[language]=en,mi`. In my case, this returns all records without language. This is a great [documentation](http://digitalnz.org/developers/api-docs-v3/search-records-api-v3) for `v3` API. It includes `or`, `and`, `without` and more.

The `&fields=format` issue could be fixed by doing a re-index. Same with `publisher` field. 

Let me know if that works.

**Note:**

This is my workflow for re-indexing records manually.

```bash
$ docker exec -it api rails c
> Sunspot.session = Sunspot::Rails.build_session
> SupplejackApi::Record.all.map(&:index)
> Sunspot.commit
```

While you're inside the Rails console, check if you have the changes on your RecordSchema by running this:

```
> puts JSON.pretty_generate RecordSchema.fields.as_json
```

**Comment by revanar** [comment]
Hi @hapiben,

When I attempted to use your re-indexing workflow, I got the following ouput:

```ruby
> Sunspot.session = Sunspot::Rails.build_session
```
`=> #<Sunspot::SessionProxy::ThreadLocalSessionProxy:0x0055f2a6f827c8 @config=#<LightConfig::Configuration:0x0055f2a34ee7b0 @properties={:solr=>#<LightConfig::Configuration:0x0055f2a34ee300 @properties={:url=>"http://solr:8983/solr", :read_timeout=>nil, :open_timeout=>nil}>, :master_solr=>#<LightConfig::Configuration:0x0055f2a6f77be8 @properties={:url=>nil}>, :pagination=>#<LightConfig::Configuration:0x0055f2a6f77828 @properties={:default_per_page=>30}>, :indexing=>#<LightConfig::Configuration:0x0055f2a6f77468 @properties={:default_batch_size=>50}>}>>`

```ruby
> SupplejackApi::Record.all.map(&:index)
```
```ruby
ArgumentError: too few arguments
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/data_extractor.rb:17:in `format'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/data_extractor.rb:17:in `value_for'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/field_factory.rb:58:in `populate_document'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:100:in `block in prepare'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:99:in `each'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:99:in `prepare'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:25:in `block in add'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:25:in `map'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:25:in `add'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/session.rb:91:in `index'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index'
	from /bundle/gems/sunspot-2.2.0/lib/sunspot.rb:184:in `index'
	from /bundle/gems/sunspot_rails-2.2.0/lib/sunspot/rails/searchable.rb:392:in `solr_index'
	from /bundle/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:648:in `yield_document'
	from /bundle/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:123:in `block in each'
	from /bundle/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `block in each'
	from /bundle/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
	from /bundle/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
	from /bundle/gems/moped-2.0.7/lib/moped/query.rb:78:in `each'
	from /bundle/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:122:in `each'
	from /bundle/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:245:in `map'
	from /bundle/gems/mongoid-4.0.0/lib/mongoid/contextual/mongo.rb:245:in `map'
	from /bundle/gems/mongoid-4.0.0/lib/mongoid/contextual.rb:20:in `map'
	from (irb):3
	from /bundle/gems/railties-4.1.14.1/lib/rails/commands/console.rb:90:in `start'
	from /bundle/gems/railties-4.1.14.1/lib/rails/commands/console.rb:9:in `start'
	from /bundle/gems/railties-4.1.14.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /bundle/gems/railties-4.1.14.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /bundle/gems/railties-4.1.14.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
```

After committing, I had no difference in my results. Do you have any ideas of what may be causing this issue?  Also, I'm curious... How does your workflow differ from using the 'Reindex Data Source' button in the Manager interface?

Once again, thank you for always being so helpful!

-Matt

**Comment by hapiben** [comment]
Hi @revanar,

Nice. I haven't thought about that `format` issue. Nice catch. Just let me know if you have issues. Happy here to help. 👍 

Ben

**Comment by revanar** [comment]
Thanks, @hapiben!

I am a bit curious... does the "Reindex Data Source" button in the manager interface actually do anything? It always tells me it's starting to index when I use it, but it never actually seems to do anything, as far as I can tell.
