### ISSUE TITLE
An oddity with facet searches and wildcards

### ISSUE THREAD

**Issue by revanar** [DigitalNZ/supplejack_docker#12]
Hi @hapiben,

This isn't really a big issue, and isn't urgent, but I noticed something interesting while playing around with metadata retrieval in the API.

When performing facet searches, if you don't include an empty set of brackets at the end of your query param, you can use wildcards in your search params.  So, for instance, if you search `&and[subject]=Coas*`, it could return a result like `subject: ["Coast Salish mythology"]`.  However, when you add the empty brackets to your param (eg `&and[subject][]=Coas*`), the wildcard no longer works, so no results would be returned with said search. That said, the empty brackets are required to provide multiple search parameters on the same facet (eg `&and[subject][]=Coast+Salish+mythology&and[subject][]=place+(Philosophy)`). 

So it seems like what it amounts to is that you is that you can only perform wildcard searches on facets if you don't want to have multiple search parameters for the same facet, which seems a bit odd. Is there something that I'm doing wrong / misunderstanding, or is this just something that Supplejack's API is not built to do? 

Edit:
I've noticed that with text searches, this is not the case.  `&text=Sal*+Coa*` will match anything that has a single field containing a word starting with "Sal" and a word starting with "Coa".  `&text=OR+Sal*+Coa*` will match anything containing either one of the two.  But with regards to this, I'm curious if there are ways to perform more complex boolean searches.  For instance, would there be a way to search for something like ("Salish Coast") OR ("audio" OR "interview")?

**Comment by hapiben** [comment]
Hi @revanar,

The wildcard `(*)` for multiple search criteria is interesting. I tried it on our production API and it does have the same behavior as yours. Looking at https://lucene.apache.org/core/2_9_4/queryparsersyntax.html, there's no mention of having wildcards for `AND`, `OR` and other operators.

The API queries that we're doing are translated to a Solr query. You can pass `&debug=true` to see the actual Solr query.

I believe this is something that we can do. I guess the reason for us not to have that feature is most of the facets that we are using don't require wildcards and being used as sidebar filter for websites such as Natlib and DNZ.

For the text search, I think you don't need the wildcards `(*)`. I haven't tried the groupings, but having `&text="Salish Coast" OR "audio" OR "interview"` should work.

**Comment by revanar** [comment]
Thanks for the info, @hapiben.

I was mostly curious about exploring the possibilities for the API, so I'd have a better idea of what sorts of components it makes sense to build into a client.  Knowing that wildcards aren't built to be functional in facet searches means that I'll likely avoid making any sort of Advanced Search feature that allows individuals to enter text for a facet search, since it seems like it wouldn't be very likely that they'd be able to get any results if they didn't already know the exact facet value they were looking for.  But since sidebar filters tend to be a bit more usable anyway, I don't think this is a problem.

Looking over the query parser syntax, I see that there are quite a few things that we can do with text searches that I wasn't aware of before (such as fuzzy searching).  I feel like I have a lot to think about now with regards to how to design the most useful search engine!

Thanks again for the help!
