### ISSUE TITLE
Figuring out how to use code snippets.

### ISSUE THREAD

**Issue by revanar** [DigitalNZ/supplejack_docker#13]
Hi @hapiben,

I don't know at this point if this is the right place to bring this issue, because it may be a general issue with Supplejack, rather than a specific issue with the Docker build, but I'm working on understanding code snippets right now, and I seem to be running into issues.

In the [supplejack documentation](http://digitalnz.github.io/supplejack/manager/code-snippets.html), it sounds like you could create a snippet like this:

Snippet name ("OAI Default Fields")
```ruby
attribute :title, xpath: '//dc:title'
attribute :description, xpath: '//dc:description'
attribute :display_date, xpath: '//dc:date'
```

And then call the snippet in a parser:
```ruby
class Brock < SupplejackCommon::Oai::Base
  base_url "http://dr.library.brocku.ca/oai/request"
  
  namespaces dc: "http://purl.org/dc/elements/1.1"

  include_snippet "OAI Default Fields"

  attribute :internal_identifier, xpath: '/record/header/identifier'
  attribute :display_content_partner, default: 'Brock University'
end
```

When I do this, and then preview it, it shows the content of the snippet is being harvested successfully.  However, when I actually run a harvest, the resulting records don't have any of the fields that were in the code snippet.  Is there something wrong with my syntax, or with my understanding of how code snippets ought to be working?

Thanks,

-Matt

**Comment by hapiben** [comment]
Hi @revanar,

Can you try to tag your snippet named `OAI Default Fields` as `staging`. I think this is not covered in the documentation. But it is important to tag the snippet same as the environment of the parser that uses it.

If you have the `Brock` parser tagged as production and staging, you need to tag the snippet with production and staging as well to make the harvesting works.

Hope it helps. Let me know if it works.

Ben

**Comment by revanar** [comment]
That did it! Once again, you had a simple solution to a problem I've been stuck on for days!  Thanks for the help, @hapiben!

**Comment by hapiben** [comment]
You're welcome @revanar. Glad it works! 👍
