### ISSUE TITLE
Performing enrichments

### ISSUE THREAD

**Issue by revanar** [DigitalNZ/supplejack_docker#14]
Hi @hapiben,

I've been trying to figure out how to do enrichments to fetch additional metadata, but I'm not making much headway.

Here's my parser at the moment:

```ruby
class Waterloo < SupplejackCommon::Oai::Base
  
  namespaces mets: "http://www.loc.gov/METS/"

	base_url "https://uwspace.uwaterloo.ca/oai/request" #change to match new source
	
	#snippets
	include_snippet "OAI DC Metadata"
	
	#static attributes
	attribute :display_content_partner, default: 'University of Waterloo' #change to match new source
	
	#add new dynamic attributes here
  
  #doesn't seem to be working, and i'm not sure why.
  enrichment :thumbnail do
    requires :handle do
      part1 = primary[:source_url].split(3)
      part2 = primary[:source_url].split(4)
      compose(part1, "/", part2, "/")
    end
    
    url "https://uwspace.uwaterloo.ca/metadata/handle/#{requirements[:handle]}/mets.xml"
    format "xml"
  	
  attribute :thumbnail_url, xpath: "//mets:fileSec/fileGrp[@USE=\'THUMBNAIL\']/FLocat/@xlink:title"
    
  end
end
```

In this schema, the `:source_url` attribute is defined in the `OAI DC Metadata` snippet, and the goal of the enrichment is to go to the METS metadata page for a record that was parsed from its OAI metadata, and fetch the thumbnail using xpath.

However, the enrichment doesn't seem to be working -- it's not showing up in previews, and when I perform an enrichment on my ingested metadata, it sets the `:thumbnail_url` of each record item as `null`.

I'm not sure what's going wrong with this, or what I can do to be able to better troubleshoot this. Do you have any thoughts on what I may be doing wrong, or any advice on how to troubleshoot enrichments?

I tried posting about this on the supplejack_manager git page, but haven't gotten any response there yet.

Thanks again for all your help!

-Matt

**Comment by dan-dnz** [comment]
Hi @revanar,

Sorry it took so long to get back to you. I added a few things to your code above and got an equivalent working from those 2 data sources. Have a go with this and let me know how it goes:

```ruby
class Waterloo < SupplejackCommon::Oai::Base
	
  base_url "https://uwspace.uwaterloo.ca/oai/request"
  
  # namespaces are a bit of a pain. You need to declare any you use, even those in the enrichment up here
  namespaces mets: 'http://www.loc.gov/METS/',
               dc: 'http://purl.org/dc/elements/1.1/',
            xlink: 'http://www.w3.org/TR/xlink/'
  
  attribute :display_content_partner, default: 'University of Waterloo' 
	
  # Snippets
  include_snippet "OAI DC Metadata"	
  # Which I guess has something like this in it
  # attribute :source_url do
  #  fetch("//dc:identifier")
  # end
  
  # ===== start of enrichment block =======
  enrichment :test_enrich, priority: -4, required_for_active_record: false do 
	
    requires :enrich_url do
      # gets the source_url from the primary harvest. 
      # then uses a mapping regex to grab the bit it needs and put it into the url (\1)
      primary[:source_url].mapping(/^.*handle\.net(.*)$/ => 'https://uwspace.uwaterloo.ca/metadata/handle\1/mets.xml').first 
    end
	
    format :xml # specefies what the resource will be (xml, html, json)
	
    # Rather than doing the url manipulation down here, I find its easier to get it all sorted in the 'requires' block up above.
    url "#{requirements[:enrich_url]}"
	 
    # I sometimes comment out all other attributes and use this for debugging to confirm the right url is being called
    # attribute subject, default: "#{requirements[:enrich_url]}"
	  
    attribute :thumbnail_url do
      # xpath needed a double // before the mets:FLocat. And needed the namespaces declared up top
      fetch("//mets:fileSec/mets:fileGrp[@USE='THUMBNAIL']//mets:FLocat/@xlink:title")
    end
	    
  end 
  # ===== end of enrichment block =======

end
```

Cheers
Dan

**Comment by revanar** [comment]
Hi @dan-dnz, thanks for the response.  I'm testing this enrichment now to see if it works for me, and I'll let you know!  I have had trouble getting enrichments I've attempted to actually show up on records both in the preview function and in the actual active records, but I'm hoping for the best!

**Comment by revanar** [comment]
@dan-dnz, Okay, so I tested this enrichment, and I found that:

- When I use the debugging attribute that you had in your example, I got the correct url (I could pasted it into my browser and resolve to the page I want to get the additional metadata from)
- When I use the `:thumbnail_url` attribute in your example, nothing happens when the enrichment is run.  It seems to spend quite awhile trying, but then nothing happens.

Is there any way to get a more verbose output from enrichments so I can see where it's going wrong? Can you think of anything that would be preventing this from working that I could try?

For reference, here is an example of one of the pages I'm trying to harvest metadata from for enrichment purposes: [https://uwspace.uwaterloo.ca/metadata/handle/10012/662/mets.xml?isAllowed=y](url).

As always, thanks for all the help!

**Comment by dan-dnz** [comment]
Hi @revanar,

Improving the experience of working in enrichments is right up near the top of our Supplejack backlog as it can be quite tricky troubleshooting any issues. Here's a couple of things that might be useful.
My suspicion is that its the fetch or the namespaces that are causing the problem.

#### Confirm that there is not an issue with that field specifically
```
    attribute :thumbnail_url do
      # fetch("//mets:fileSec/mets:fileGrp[@USE='THUMBNAIL']//mets:FLocat/@xlink:title")
      "working fine" # If you see this come back in a preview, then the field itself is not to blame.
    end
```

#### Using `puts` for a bit more logging info
```
    attribute :thumbnail_url do
      puts "sj_debug_log: inside :thumbnail_url - before the fetch"
      result = fetch("//mets:fileSec/mets:fileGrp[@USE='THUMBNAIL']//mets:FLocat/@xlink:title")
      puts "sj_debug_log: inside :thumbnail_url - after the fetch"
      puts "sj_debug_log: Fetch result - #{result.to_s} -" # not really sure if this will be useful
      result
    end
```
Try tailing your equivalent sidekiq log with something like this (then previewing with the above code):
`tail -f <your_setup>/log/sidekiq.log | grep sj_debug_log`

#### Variations on the xpath to rule out namespaces
`fetch("//*[4]") # try and get anything at all back without using namespaces`
In the case of your example mets.xml lookup this should hopefully return "1998".

#### Try using node rather than fetch
Play around with something like this `node("//*[3]/text()").map(&:text)` or `node("//mets:FLocat/@xlink:title").map(&:text)` in place of the fetch in the thumbnail attribute.

Good luck. Let me know how it goes.
Apologies if my troubleshooting techniques are a bit crude, I am not really a real programmer.

**Comment by revanar** [comment]
Thanks for providing these strategies, @dan-dnz.  I don't feel like I'm really a real programmer either, and I think your debugging techniques are about on par with what I would do.  Just knowing how to do them in this environment helps. I know you guys are a small team, and I appreciate all of the help you've been willing to give us over here in Canada.  I'm hoping that once we produce a successful prototype here, it will lead to more adoption and more potential for us to start contributing to Supplejack as well!

**Comment by revanar** [comment]
--Update--

It's been awhile, but I finally made a breakthrough with this:

When I declare the namespace in my fetch command:
```
fetch('//mets:fileGrp[@USE="THUMBNAIL"]/mets:file/mets:FLocat/@ID', [:mets])
```
I am able to successfully get back namespace results.  However, it doesn't seem to work with attributes that have namespaces.  When I try the following, it doesn't work:
```
fetch('//mets:fileGrp[@USE="THUMBNAIL"]/mets:file/mets:FLocat/@xlink:href', [:mets, :xlink])
```

I've tried a few variations of syntax for the href attribute, but none of them seem to have solved it.  So, this is the point I'm at now.  If you have any thoughts on the matter, I'd appreciate them.  I'll also keep trying to come up with other things to try in the meantime, though.

-Matt

**Comment by revanar** [comment]
It took a long time, but I was finally able to figure out the issue, and how to solve it.

It turns out that it wasn't failing with namespaces on elements---just when namespaces were on attributes.  I was able to find a way to fetch the value of a namespaced attribute in xpath without having to declare its namespace, though:

```
`fetch('//mets:fileGrp[@USE="THUMBNAIL"]/mets:file/mets:FLocat/@*[local-name()="href"]')`
```
