### ISSUE TITLE
API admin access

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#15]
Hi @hapiben, 

Can you tell me if the API admin console is enabled in the docker_repo? The passwords given at: http://digitalnz.github.io/supplejack/api/api-admin.html  

`
    email: test@example.com
    password: supplejack
`

Don't seem to be effective, nor does generating my own user/password on the rails console. 

Thanks, 

D.

**Comment by hapiben** [comment]
Hi @telezoic 

Sorry for my late response. The default username and password for the API admin can be found here: https://github.com/DigitalNZ/supplejack_api_app/blob/master/lib/tasks/docker.rake

You can always create a new user using `rails console` under `API`.

Ben
