### ISSUE TITLE
file harvest location

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#16]
Hi @hapiben,

Sorry to be at you with questions regularly. I noticed in the docs and screenshot some parsers specify a file location, like:
`base_url "file:////data/arts.xml"`

Can you tell us where we can place a file so that it's accessible to the parser? We we're thinking maybe: `manager/lib/assets` but that doesn't seem to the place . . . 

Thanks,

D

**Comment by hapiben** [comment]
Hi @telezoic 

I suggest put it inside a data folder `manager/data`. The location doesn't really matter as long as it has the correct permission to be read by the manager.

Ben

**Comment by dan-dnz** [comment]
And if you're still having trouble, try less /'s.
Looking at some of my parsers that use local files, there is only 3 backslashes at the start of the base_url location. So you could try something more like:
`base_url "file:///data/arts.xml"`

Dan

**Comment by telezoic** [comment]
Thanks Ben/Dan. 

I've put my file in `manager/data` and set perms wide open: 
`drwxrwxrwx+  3 daniel  staff    102  1 Mar 14:15 data`
`-rwxrwxrwx@  1 daniel  staff  208976 27 Feb 12:02 odwMods1.xml`

I'm testing out a variety of slashes and path lengths in my harvester with this (as a base)
` base_url "file:///data/odwMods1.xml"`

Without fail, I'm getting a an error in the harvester preview,  and it appears the parser can't find the file. 

`Errno::ENOENT`
`No such file or directory @ rb_sysopen - /data/odwMods1.xml`


On a whim I tried to load it to a webserver and call it from there (with permissions open)
using `base_url: "http://159.203.21.122/data/odwMods1.xml"`. With the idea that I could treat if like an html/xml harvest (as per the docs) but here my preview just spins forever.

Not sure if you had any further suggestion or pointers for us . . . I feel like I'm missing something.

Again, thanks for all your assistance and patience with our queries. 

D.

**Comment by hapiben** [comment]
Hi @telezoic 

Sorry for late response. What I think the problem is, the manager tries to access the file from the root folder of Unix because of the `/data`. Instead of putting the file inside the manager, can you create a folder in your root directory called `/data` and put the file there?

Otherwise, you can use the absolute path of the file as `base_url`. e.g. `/data/sites/manager/data/file.xml`

**Comment by telezoic** [comment]
Thanks Ben, 

Sorry about the delay. We finally got it by placing our data folder in `/worker,` and then `docker-compose stop/build/up` [all] and `base_url "file:///worker/dataW/odwMods2.xml"`

👍 

D

**Comment by hapiben** [comment]
Nice. 👍 

No worries.
