### ISSUE TITLE
Date range searches

### ISSUE THREAD

**Issue by revanar** [DigitalNZ/supplejack_docker#17]
Hi @hapiben,

I'm trying to figure out how to create a date range search for our Supplejack instance.  I noticed that on the DigitalNZ Supplejack instance, date searches seem to rely on this set of API params:

```
i[year_type]=date&i[start_year]=1990&i[end_year]=2020
```

I tried the following:

In my `record_schema.rb`, I added:

```
datetime :date, namespace: :sj
```

In my parser, I have:

```
attribute :date, xpath: '//dc:date'
```

Then, after indexing my records, I performed the API call `http://192.168.99.100:3000/records.json?api_key=apikey&fields=title,date&i[year_type]=date&i[start_year]=2010&i[end_year]=2011`

And got a response formatted like:
```
{
  "search": {
    "result_count": 30,
    "results": [
      {
        "title": "Plan of the Grand Central Hotel",
        "date": "2009-01-27T19:06:52.000+00:00"
      },
...
```

So, it doesn't seem to be working, but I'm not sure what needs to be adjusted to make it work.  Do you have any light you could shed on this issue?

Again, thank you so much for all of the help you've given us on getting this up and running!

-Matt

**Update**

I just realized that this same search doesn't seem to work even with the DigitalNZ Supplejack instance, so there must be some other step I'm not understanding!

**Comment by hapiben** [comment]
Hi @revanar,

Apologies for my late response.

Supplejack date search for range works like Solr query. If you want a year range, you can do something like this:

`&and[year]=[1500 TO 1600]`

More information about Solr date range search can be found [here](https://cwiki.apache.org/confluence/display/solr/Working+with+Dates).

Let me know how it goes.

Ben

**Comment by revanar** [comment]
Hi Ben.  It definitely helps now that I know what the API request should look like, but I still seem to be running into some issues getting it to work on our end.

In `record_schema.rb`, I have:
```ruby
  datetime  :date,                        multi_value: true,    search_as: [:filter],             namespace: :sj
```

And in the parser:
```ruby
  attribute :date, xpath: '//dc:date', date: true
```

With these, the api request: `&fields=title,date`, gives the following result format:
```json
{
  "title": "Plan of the Grand Central Hotel",
  "date": [
    "2009-01-27 19:06:52 UTC"
  ]
},
```

However, the request: `&fields=title,date&and[date]=[2008 TO 2010]`, gives the error, `undefined method 'map' for nil:NilClass`, with a stack trace starting at `/bundle/bundler/gems/supplejack_api-c6b0c27aff5c/app/serializers/supplejack_api/record_search_serializer.rb:20`

I also tried creating a `year` field to search, as shown in: https://github.com/DigitalNZ/supplejack_api/blob/fc432650a8e604bc6b885d2d17459f5b19a17b88/spec/models/supplejack_api/schema_definition_spec.rb

However, even though i confirmed with some `puts` commands that it was catching the years correctly, when I attempted to search `&and[year]=[2008 TO 2010]`, I just got a blank page.

Any thoughts on what I might be doing wrong?

**Comment by dan-dnz** [comment]
Hi @revanar 

I've got a few things you might like to try, although I'm not sure any of them will be useful.

1. `&debug=true`
I'm not sure if you've come across this parameter, or in fact if it is even available in the opensource supplejack? But throwing that onto any API query shows some extra solr request info in the response:

>solr_request_params: {
  fq: [
    "type:Record",
    "record_type_i:0",
    "-source_id_s:auckland\-heritage\-images",
    "year_im:[1940 TO 1950]"
  ],

**Comment by dan-dnz** [comment]
Hi @revanar

I've got a few things you could try, although I'm not sure any of them will be any use.

1. `&debug=true`
I'm not sure if you've come across this parameter, or in fact if it is even available in the opensource supplejack? But throwing that parameter onto any API query shows some extra solr request info in the response:
>solr_request_params: {
fq: [
"type:Record",
"record_type_i:0",
"-source_id_s:auckland-heritage-images",
"year_im:[1940 TO 1950]"
],

2. `&and[year]=[2008+TO+2010]`
In your last comment you mentioned `date` but it needs to be `year` (otherwise I get a 500 error)

3. `&per_page=0&facets_per_page=100&facets=year,date`
I'm not sure which fields you have set up for faceting, but it could help confirm that the metadata is in the right place.

Hopefully this helps.

Dan.

**Comment by revanar** [comment]
HI Dan,

I think what I'm unclear about is how to get the `year` data to populate correctly in the first place.  At the moment I have this in my `record_schema.rb`, but it doesn't seem to be working:

```
  datetime  :date,                        multi_value: true,    search_as: [:filter],             namespace: :sj

  integer :year do
        multi_value true
        search_as [:filter]
        search_value do |record|
          result = record.date.collect {|date| Date.parse(date).year rescue nil}.compact if record.date
	  puts result
          result
        end
      end
```

**Comment by dan-dnz** [comment]
Yeah that looks a little strange.

Its probably not this, but just to be sure, give the year param a go with an extra set of square brackets (which I think are required sometimes but I never usually use them)
`&and[year][]=1990&debug=true`
Whether I use the extra [] or not, I get the following for the above call:
>solr_request_params: {
fq: [
"type:Record",
"record_type_i:0",
"year_im:(1990)",
null
],

Something that is hopefully a little more useful, try simplifying the call a little (pick a year you know you have content) and then try putting the solr query in the text parameter (which you can do if you know the exact solr field name).
`&text=year_im:1990&debug=true`
For me this works, and returns:
>solr_request_params: {
fq: [
"type:Record",
"record_type_i:0",
null
],
q: "year_im:1990",

Not really sure why it splits the call out into `q:` in the response.
Ideally we just want to see solr receiving the request correctly through to the `solr_request_params`.

Out of interest, I tried intentionally making a call of `year_im:0` which is what your requests appear to be doing. This gave me 0 results.
`&text=year_im:0&debug=true`


Dan.

**Comment by revanar** [comment]
So, an interesting thing is that single date searches work correctly for me.  So:

`http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&and[year]=1960`
yields:
```
"solr_request_params": {
      "fq": [
        "type:SupplejackApi\\:\\:Record",
        "record_type_i:0",
        "year_im:1960",
        null
      ],
      "start": 0,
      "rows": 20,
      "q": "*:*"
    },
```

and `http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&and[year][]=1960`
or `http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&and[year][]=1960 TO 1980`
yields:
```
"solr_request_params": {
      "fq": [
        "type:SupplejackApi\\:\\:Record",
        "record_type_i:0",
        "year_im:(1960)",
        null
      ],
      "start": 0,
      "rows": 20,
      "q": "*:*"
    },
```

But `http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&and[year][]=[1960]`
or `http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&and[year][]=[1960 TO 1980]`
yeilds:
```
 "solr_request_params": {
      "fq": [
        "type:SupplejackApi\\:\\:Record",
        "record_type_i:0",
        "year_im:(0)",
        null
      ],
      "start": 0,
      "rows": 20,
      "q": "*:*"
    },
```

As for the manual calls, 

`http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&text=year_im:1960`
Provides the correct results, with these params:
```
"solr_request_params": {
      "fq": [
        "type:SupplejackApi\\:\\:Record",
        "record_type_i:0",
        null
      ],
      "q": "year_im:1960",
      "fl": "* score",
      "qf": "title_text description_text display_content_partner_text display_collection_text",
      "defType": "edismax",
      "start": 0,
      "rows": 20
    },
```

But `http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&text=year_im:[1960]`,
`http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&text=year_im:[1960 TO 1980]`,
and `http://192.168.99.100:3000/records.json?api_key=apikey&debug=true&text=year_im:1960 TO 1980`, and every other variation I tried shows the query I gave it, eg `"q": "year_im:1960 to 1980",`, but doesn't give any results.

Overall, it seems like it's not understanding search parameters that are sent to it in brackets, but looking at the Solr documentation, that's the expected format.  Do you see any differences between the schema I sent you, and the one you guys are using that might account for that?

Once again, thanks for all of your help!

**Comment by revanar** [comment]
An update to this: 

Looking at the dev logs for these requests, I notice that the request is going in as a string:
```
Parameters: {"api_key"=>"apikey", "debug"=>"true", "and"=>{"year"=>"[1950 TO 1980]"}, "version"=>nil}
```
But then is not being sent as a query to the database:
```
MOPED: 172.18.0.3:27017 QUERY database=supplejack_api_development collection=sources selector={"status"=>"suppressed"} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 0.5112ms ^[[1m^[[32mSOLR Request (6.0ms)^[[0m [ path=^[[1m^[[1mselect^[[0m parameters={fq: ^[[1m^[[1m["type:SupplejackApi::Record", "record_type_i:0", "year_im:0", nil]^[[0m, start: ^[[1m^[[1m0^[[0m, rows: ^[1m^[[1m20^[[0m, q: ^[[1m^[[1m"*:*"^[[0m} ]
Completed 200 OK in 35ms (Views: 0.8ms | Solr: 0.0ms)
```

So it looks like the issue is happening somewhere between the input and the database query, which is not surprising, but I'm wondering at this point if the issue is related to it being parsed as a string rather than as a Solr Query
