### ISSUE TITLE
Record delete/re-index

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#18]
Hi @hapiben,

We have a nagging record that breaks our manual re-index efforts. I'm thinking if I could delete it that might be a good start. Can you tell me how I obtain the `<mongo_id>` for the process you shared with me in #8:

`# Run this command using rails console inside the API container`
`Sunspot.session = Sunspot::Rails.build_session`
`Sunspot.remove_by_id(Supplejack::Record, <mongo_id_here>)`
`Sunspot.commit`

 Alternatively I was thinking I could run a manual index on only a range of items rather than all of them in `SupplejackApi::Record.all.map(&:index)` is this possible?

Thanks,

Dan

**Comment by hapiben** [comment]
Hi @telezoic 

You can obtain the Mongo ID by running this command on your console:

```bash
irb(main):001:0> SupplejackApi::Record.last.id
=> BSON::ObjectId('593da7b88d2a4e16a0002079')
```

This will give you the last record's ID. Just grab the `593da7b88d2a4e16a0002079` and put it on your `Sunspot.remove_by_id(Supplejack::Record, <mongo_id_here>)` command.

B

**Comment by telezoic** [comment]
Thanks Ben!

D.
