### ISSUE TITLE
 Service 'solr' failed to build:

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#2]
Hi There, 

When I run `docker-compose build` I invariably get a a pair of failed key imports: 

`:: Import PGP key 2048R/, "Christian Hesse (Arch Linux Package Signing) <arch@eworm.de>",` `created: 2011-08-12? [Y/n] error: key "Christian Hesse (Arch Linux Package Signing)` `<arch@eworm.de>" could not be imported`

`:: Import PGP key 4096R/, "Antonio Rojas <arojas@us.es>", created: 2014-10-21? [Y/n] error: key "Antonio Rojas <arojas@us.es>" could not be imported`

`error: required key missing from keyring`
`error: failed to commit transaction (unexpected error)`
`Errors occurred, no packages were upgraded.`
`ERROR: Service 'solr' failed to build:`

I've swapped out the keyserver in /supplejack_solr/Dockerfile with each of the keyservers listed at:
https://wiki.archlinux.org/index.php/Pacman/Package_signing, to no avail. Each time I get the error, and the build fails. Not being familiar with Arch, I'm hoping you have a tweak or suggestion for me :) . . .

Thanks, 

D.

**Comment by hapiben** [comment]
Hi @telezoic. I'll try to replicate the issue. 👍

**Comment by hapiben** [comment]
I've managed to replicate the issue. Turns out I needed to update the base Arch Linux container that we're using. If you pull the latest changes in master recursively and run `docker-compose build solr` it should build Solr for you successfully.

To run it, use `docker-compose run solr`.

**Comment by telezoic** [comment]
Thanks for this!
