### ISSUE TITLE
docker-compose up --no-recreate

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#3]
Hi @hapiben, 

I've incorporated your changes from the last issue. Thanks for this! I can now get past the build and run `docker-compose up --no-recreate`. 

When I do, I see ` No such file or directory @ rb_sysopen - /worker/tmp/pids/sidekiq.pid` 
for sidekiq.

and in the manager I get: `/usr/local/bundle/gems/bundler-1.7.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-11.2.2 in any of the sources (Bundler::GemNotFound)`.  

When  `docker-compose up --no-recreate` is done I can access all but three of the interfaces: 

`API: api.docker:3000` [YES]

`Manager: manager.docker:3001` [NO] - the Rake error?

`Worker: worker.docker:3002/sidekiq` [YES]

`Solr: solr.docker:8983/solr/#/collection1` [YES]

`MongoDB Data: Mounted in host data/db - mongodb.weave.local:27017` [NO]

`Redis: redis://redis.weave.local:6379/0` [NO]

Do you have any suggestions/tweaks/guidance you could offer on how I could get these interfaces up?

Thanks, 

Dan

**Comment by hapiben** [comment]
Hi @telezoic. I'll try to replicate this issue.

**Comment by telezoic** [comment]
Thanks!


D

On Oct 17, 2016, at 19:23, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>. I'll try to replicate this issue.

�

**Comment by hapiben** [comment]
Hi @telezoic,

I have a success replicating the issue. However, I think it'll take more time for us to fix the issue. Some of the packages and images that we use for Docker are already deprecated and Docker introduces a new way to network containers and mount volumes.

For now, we can still setup Supplejack stack in a traditional way (running apps one-by-one). I'm happy to help you with the process.

You can start [here](http://digitalnz.github.io/supplejack/start/development-setup.html).

Since you already have the `supplejack_docker` repo, you can `cd` to each component and run them using `rails s <port>`.

```ruby
API: Port 3000
Manager: Port 3001
Worker: Port 3002
```

**Comment by telezoic** [comment]
Thanks Ben. I'll try this out.


D

On Oct 19, 2016, at 15:31, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>,

I have a success replicating the issue. However, I think it'll take more time for us to fix the issue. Some of the packages and images that we use for Docker are already deprecated and Docker introduces a new way to network containers and mount volumes.

For now, we can still setup Supplejack stack in a traditional way (running apps one-by-one). I'm happy to help you with the process.

You can start here<http://digitalnz.github.io/supplejack/start/development-setup.html>.

Since you already have the supplejack_docker repo, you can cd to each component and run them using rails s <port>.

API: Port 3000
Manager: Port 3001
Worker: Port 3002

�

**Comment by hapiben** [comment]
Hi @telezoic, I've updated this repo to use the new Docker Compose 2. Part of this update is fixing common issues and removing Dinghy and Weave.

There are new instructions that you can find in the `README` file on how to get started.

I'm happy to help you out if you get stuck, just let me know.

**Comment by telezoic** [comment]
Thanks Ben. This is great! I hope to start with it next week.


D



On Oct 27, 2016, at 6:27 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @telezoic<https://github.com/telezoic>, I've updated this repo to use the new Docker Compose 2. Part of this update is fixing common issues and removing Dinghy and Weave.

There are new instructions that you can find in the README file on how to get started.

I'm happy to help you out if you get stuck, just let me know.

**Comment by jamesarobertson** [comment]
Thanks @hapiben for the great work on this, including during R&D time. I really appreciate it. Hopefully this will enable @telezoic to complete set-up of Supplejack and begin trailling.

**Comment by hapiben** [comment]
No problem @jamesarobertson.

Just a small note @telezoic. I've retested the fixes on a new docker machine and everything works well. Just a small [addition](https://github.com/DigitalNZ/supplejack_docker/commit/6efa7f4136ccdd0dc3b0baa042229fbe8923d702#diff-04c6e90faac2675aa89e2176d2eec7d8) to the instruction about the manager.

**Comment by telezoic** [comment]
Thanks @hapiben<https://github.com/hapiben>! after following your manager/config mod, my set-up is complete.

I’m really exited to start exploring this, hopefully this week.

D


On Oct 30, 2016, at 6:44 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem @jamesarobertson<https://github.com/jamesarobertson>.

Just a small note @telezoic<https://github.com/telezoic>. I've retested the fixes on a new docker machine and everything works well. Just a small addition<https://github.com/DigitalNZ/supplejack_docker/commit/6efa7f4136ccdd0dc3b0baa042229fbe8923d702#diff-04c6e90faac2675aa89e2176d2eec7d8> to the instruction about the manager.
