### ISSUE TITLE
Delete records

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#8]
Hi @hapiben, 
I was wondering if there is mechanism for deleting harvested records?

Thanks, 

D

**Comment by hapiben** [comment]
Hi @telezoic,

Currently, the way to safely delete records is to change the status of a record from `active `to  `deleted`.

Once set to `deleted` and save it, the record will be pushed into Resque's queue to re-index (after 5 mins). You can also do a manual indexing for that record.

If you want to delete the actual record like `record.destroy`, you'll end up having an orphaned index in Solr. In this case, you need to remove the record in the Solr index. To do that, you need the Mongo ID of the record.

```ruby
# Run this command using rails console inside the API container
Sunspot.session = Sunspot::Rails.build_session
Sunspot.remove_by_id(Supplejack::Record, <mongo_id_here>)
Sunspot.commit
```

**Comment by telezoic** [comment]
Hi @hapiben, 

We have a nagging record that breaks our manual re-index efforts. I'm thinking if I could delete it that might be a good start. Can you tell me how I obtain the `<mongo_id>` above? Alternatively I was thinking I could run a manual index on only a range of items rather than all of them in `SupplejackApi::Record.all.map(&:index)`  is this possible?

Thanks, 

Dan
